### ISSUE TITLE
class tuple not recognized when running de.test.pairwise

### ISSUE THREAD

**Issue by fairliereese** [theislab/diffxpy#154]
I'm trying to run multi-way tests and following [this](https://nbviewer.jupyter.org/github/theislab/diffxpy_tutorials/blob/master/diffxpy_tutorials/test/multiple_tests_per_gene.ipynb) tutorial. On the webpage, as referenced in issue [#135](https://github.com/theislab/diffxpy/issues/135), I see an assertion error. However, when trying to run this on my own machine, I get a different error, both when using my own data and when copy pasting the tutorial code. Here's the stack trace I get. 

`adata = sc.AnnData(X=np.asarray(sim.x), obs=sim.sample_description)
Transforming to str index.
>>> test = de.test.pairwise(
...     data=adata,
...     grouping="batch",
...     test="z-test",
...     lazy=False,
...     noise_model="nb"
... )
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/diffxpy/diffxpy/testing/tests.py", line 1256, in pairwise
    **kwargs
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/diffxpy/diffxpy/testing/tests.py", line 193, in _fit
    cast_dtype=dtype
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/batchglm/batchglm/models/base_glm/input.py", line 96, in __init__
    param_names=design_loc_names
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/batchglm/batchglm/models/base_glm/utils.py", line 41, in parse_design
    raise ValueError("type %s not recognized" % type(design_matrix))
ValueError: type <class 'tuple'> not recognized`

**Comment by fairliereese** [comment]
An addendum: I'm also getting an error when trying to run de.test.versus_rest on the tutorial: 

`>>> test = de.test.versus_rest(
...     data=adata,
...     grouping="condition",
...     test="wald",
...     noise_model="nb"
... )
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/diffxpy/diffxpy/testing/tests.py", line 1492, in versus_rest
    **kwargs
  File "/Users/fairliereese/Documents/programming/mortazavi_lab/bin/diffxpy/diffxpy/testing/tests.py", line 1026, in two_sample
    raise ValueError("Less than two groups detected:\n\t%s", groups)
ValueError: ('Less than two groups detected:\n\t%s', array(['group'], dtype='<U5'))`

**Comment by kawairine** [comment]
Hi, 

Has this issue already been solved ? I have the same issue.

 I think it is to due with test = 'z-test' when it complains about class 'tuple', because all other tests seem to work.

Any helps will be appreciated!

Thank you.

**Comment by eveolsza** [comment]
I am having the same error... but I couldn't run any other tests either

Any helps will be appreciated!

Thank you.
