### ISSUE TITLE
TypeError: Can't instantiate abstract class Estimator with abstract methods init_par

### ISSUE THREAD

**Issue by letaylor** [theislab/diffxpy#170]
For de.test.wald, if backend='tf1' the following error is thrown:

`TypeError: Can't instantiate abstract class Estimator with abstract methods init_par`

```
Using backend:  tf1
Traceback (most recent call last):
  File "/repo/sc_nextflow-ldev/pipelines/0035-differential_condition/bin/015-run_diffxpy.py", line 427, in <module>
    main()
  File "/repo/sc_nextflow-ldev/pipelines/0035-differential_condition/bin/015-run_diffxpy.py", line 304, in main
    noise_model='nb'
  File "/miniconda3/envs/diffxpy_tf1pt15pt3_v4/lib/python3.7/site-packages/diffxpy/testing/tests.py", line 736, in wald
    **kwargs,
  File "/miniconda3/envs/diffxpy_tf1pt15pt3_v4/lib/python3.7/site-packages/diffxpy/testing/tests.py", line 227, in _fit
    **constructor_args
TypeError: Can't instantiate abstract class Estimator with abstract methods init_par
```

**Comment by TheAustinator** [comment]
@letaylor did you end up figuring this one out?
