### ISSUE TITLE
Installation issue # Invalid version #

### ISSUE THREAD

**Issue by GuiSeSanz** [theislab/diffxpy#222]
Hello!

I'm trying to install diffxpy on a docker and I'm encountering the following error:

`root@8728334ea128:/home/scanpy/diffxpy/diffxpy-master# pip install -e .
Obtaining file:///home/scanpy/diffxpy/diffxpy-master
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running egg_info
      /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:561: UserWarning: The version specified ('refs/pull/219/head') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      /usr/local/lib/python3.8/dist-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: 'refs/pull/219/head'.
              !!
      
      
              ###################
              # Invalid version #
              ###################
              'refs/pull/219/head' is not valid according to PEP 440.
      
              Please make sure specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.
      
      
      !!
      
        warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/scanpy/diffxpy/diffxpy-master/setup.py", line 11, in <module>
          setup(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 220, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'refs-pull-219-head'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I have already installed  the batchglm and checked running `python -m unittest` with success.

What am I missing??

**Comment by QqQss** [comment]
same issue here
