### ISSUE TITLE
versus_rest Wald test returns InvalidArgumentError

### ISSUE THREAD

**Issue by peterpdu** [theislab/diffxpy#80]
I'm running `de.test.versus_rest` using a scanpy anndata object input that has been clustered using the Leiden algorithm. I eventually get an InvalidArgumentError saying "Input matrix was rank deficient or ill-conditioned." Has this error come up in your testing?

I'm using diffxpy v0.5 and batchglm v0.5. The full traceback is below:

Command:
```test = de.test.versus_rest(adata, grouping='leiden', test='wald', noise_model='nb', dtype='float64')```

Traceback:
```INFO:diffxpy.testing.base:Fitting model...
/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
INFO:tensorflow:Graph was finalized.
2019-03-07 13:45:20.858824: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-07 13:45:20.860698: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: Input matrix was rank deficient or ill-conditioned. Try setting fast=False or provide a larger l2_regularizer > 0.
	 [[{{node MatrixSolveLs_2}} = MatrixSolveLs[T=DT_DOUBLE, fast=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](GatherV2_56000, ExpandDims_55998, MatrixSolveLs_2/l2_regularizer)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-89-415beb4e5cb9> in <module>()
----> 1 test = de.test.versus_rest(adata, grouping='leiden', test='wald', noise_model='nb', dtype='float64')

~/computation/frameworks/diffxpy/diffxpy/testing/base.py in versus_rest(data, grouping, as_numeric, test, gene_names, sample_description, noise_model, pval_correction, size_factors, batch_size, training_strategy, quick_scale, dtype, keep_full_test_objs, **kwargs)
   3651             size_factors=size_factors,
   3652             dtype=dtype,
-> 3653             **kwargs
   3654         )
   3655         pvals[0, i] = de_test_temp.pval

~/computation/frameworks/diffxpy/diffxpy/testing/base.py in two_sample(data, grouping, as_numeric, test, gene_names, sample_description, noise_model, size_factors, batch_size, training_strategy, quick_scale, dtype, **kwargs)
   3242             quick_scale=quick_scale,
   3243             dtype=dtype,
-> 3244             **kwargs
   3245         )
   3246     elif test.lower() == 'lrt':

~/computation/frameworks/diffxpy/diffxpy/testing/base.py in wald(data, factor_loc_totest, coef_to_test, formula_loc, formula_scale, as_numeric, init_a, init_b, gene_names, sample_description, dmat_loc, dmat_scale, constraints_loc, constraints_scale, noise_model, size_factors, batch_size, training_strategy, quick_scale, dtype, **kwargs)
   3013         quick_scale=quick_scale,
   3014         dtype=dtype,
-> 3015         **kwargs,
   3016     )
   3017 

~/computation/frameworks/diffxpy/diffxpy/testing/base.py in _fit(noise_model, data, design_loc, design_scale, constraints_loc, constraints_scale, init_model, init_a, init_b, as_numeric, gene_names, size_factors, batch_size, training_strategy, quick_scale, close_session, dtype)
   2593             training_strategy(estim)
   2594         else:
-> 2595             estim.train_sequence(training_strategy=training_strategy)
   2596 
   2597         if close_session:

~/computation/frameworks/batchglm/batchglm/train/tf/base_glm_all/estimator.py in train_sequence(self, training_strategy)
    344             self.model.model_vars.converged = False
    345             logger.info("Beginning with training sequence #%d", idx + 1)
--> 346             self.train(**d)
    347             logger.info("Training sequence #%d complete", idx + 1)
    348 

~/computation/frameworks/batchglm/batchglm/train/tf/base_glm_all/estimator.py in train(self, learning_rate, convergence_criteria, loss_window_size, stopping_criteria, train_mu, train_r, use_batching, optim_algo, *args, **kwargs)
    328                           loss=loss,
    329                           train_op=train_op,
--> 330                           **kwargs)
    331 
    332     def train_sequence(self, training_strategy):

~/computation/frameworks/batchglm/batchglm/train/tf/base/estimator.py in train(self, use_stop_hooks, *args, **kwargs)
    463                 tf.logging.info("Step: %d\tloss: %f" % (train_step, loss_res))
    464         else:
--> 465             super().train(*args, **kwargs)

~/computation/frameworks/batchglm/batchglm/train/tf/base/estimator.py in train(self, learning_rate, feed_dict, convergence_criteria, loss_window_size, stopping_criteria, loss, train_op, *args, **kwargs)
    241                 train_step, global_loss, _ = self.session.run(
    242                     (self.model.global_step, loss, train_op),
--> 243                     feed_dict=feed_dict
    244                 )
    245                 # Evaluate convergence metric:

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
    669                           feed_dict=feed_dict,
    670                           options=options,
--> 671                           run_metadata=run_metadata)
    672 
    673   def run_step_fn(self, step_fn):

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1154                               feed_dict=feed_dict,
   1155                               options=options,
-> 1156                               run_metadata=run_metadata)
   1157       except _PREEMPTION_ERRORS as e:
   1158         logging.info('An error was raised. This may be due to a preemption in '

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1253         raise six.reraise(*original_exc_info)
   1254       else:
-> 1255         raise six.reraise(*original_exc_info)
   1256 
   1257 

~/anaconda2/envs/py3/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1238   def run(self, *args, **kwargs):
   1239     try:
-> 1240       return self._sess.run(*args, **kwargs)
   1241     except _PREEMPTION_ERRORS:
   1242       raise

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1310                                   feed_dict=feed_dict,
   1311                                   options=options,
-> 1312                                   run_metadata=run_metadata)
   1313 
   1314     for hook in self._hooks:

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1074 
   1075   def run(self, *args, **kwargs):
-> 1076     return self._sess.run(*args, **kwargs)
   1077 
   1078   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: Input matrix was rank deficient or ill-conditioned. Try setting fast=False or provide a larger l2_regularizer > 0.
	 [[node MatrixSolveLs_2 (defined at /Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py:398)  = MatrixSolveLs[T=DT_DOUBLE, fast=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](GatherV2_56000, ExpandDims_55998, MatrixSolveLs_2/l2_regularizer)]]

Caused by op 'MatrixSolveLs_2', defined at:
  File "/Users/pdu/anaconda2/envs/py3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 485, in mainloop
    self.interact()
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 476, in interact
    self.run_cell(code, store_history=True)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-89-415beb4e5cb9>", line 1, in <module>
    test = de.test.versus_rest(adata, grouping='leiden', test='wald', noise_model='nb', dtype='float64')
  File "/Users/pdu/computation/frameworks/diffxpy/diffxpy/testing/base.py", line 3653, in versus_rest
    **kwargs
  File "/Users/pdu/computation/frameworks/diffxpy/diffxpy/testing/base.py", line 3244, in two_sample
    **kwargs
  File "/Users/pdu/computation/frameworks/diffxpy/diffxpy/testing/base.py", line 3015, in wald
    **kwargs,
  File "/Users/pdu/computation/frameworks/diffxpy/diffxpy/testing/base.py", line 2583, in _fit
    **constructor_args
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/glm_nb/estimator.py", line 53, in __init__
    dtype=dtype
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm_all/estimator.py", line 206, in __init__
    dtype=dtype
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm_all/estimator_graph.py", line 554, in __init__
    dtype=dtype
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py", line 682, in _run_trainer_init
    train_r=train_scale
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py", line 269, in __init__
    psd=True  # TODO proove
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py", line 321, in build_updates
    psd=psd
  File "/Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py", line 398, in newton_type_update_full_byfeature
    fast=psd and pkg_constants.CHOLESKY_LSTSQS
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/linalg_ops.py", line 305, in matrix_solve_ls
    matrix, rhs, l2_regularizer, fast=fast, name=name)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1297, in matrix_solve_ls
    l2_regularizer=l2_regularizer, fast=fast, name=name)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/pdu/anaconda2/envs/py3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input matrix was rank deficient or ill-conditioned. Try setting fast=False or provide a larger l2_regularizer > 0.
	 [[node MatrixSolveLs_2 (defined at /Users/pdu/computation/frameworks/batchglm/batchglm/train/tf/base_glm/estimator_graph.py:398)  = MatrixSolveLs[T=DT_DOUBLE, fast=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](GatherV2_56000, ExpandDims_55998, MatrixSolveLs_2/l2_regularizer)]]```

**Comment by davidsebfischer** [comment]
Thanks for the issue @peterpdu! And sorry for the long delay. This behaviour may have been caused my two different issues that we addressed in the mean time. This should not occur anymore if you use code from the dev branches of diffxpy and batchglm.

**Comment by davidsebfischer** [comment]
Just reopen the issue if you still see this!
